language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - docker
sudo: false
env:
 global:
   - PRE_INSTALL_HOOK="cd /home/opam/opam-repository && git pull origin master && opam update -u -y"
   - PACKAGE="mirage-fs-unix"
   - TESTS="true"
 matrix:
   - DISTRO=alpine OCAML_VERSION=4.04.2
   - DISTRO=alpine OCAML_VERSION=4.06.0
